### GET request for products by category id
GET http://localhost:8080/api/products?catId=1

### GET request for products by category id (wrong catId)
GET http://localhost:8080/api/products?catId=55

### GET a product by product id
GET http://localhost:8080/api/products/35

### GET a product by product id (wrong product id)
GET http://localhost:8080/api/products/235

### POST to add new product
POST http://localhost:8080/api/products
Content-Type: application/json

{
   "productName": "New product",
   "categoryId": 1,
   "quantityPerUnit": "2lb per pkg",
   "unitPrice": 18.98,
   "unitsInStock": 78,
   "unitsOnOrder": 20,
   "reorderLevel": 80
}

### PUT to update product
PUT http://localhost:8080/api/products/89
Content-Type: application/json

{
   "productName": "New super product",
   "categoryId": 1,
   "quantityPerUnit": "5lb per pkg",
   "unitPrice": 28.98,
   "unitsInStock": 18,
   "unitsOnOrder": 20,
   "reorderLevel": 15
}

### PUT to update product (wrong product id)
PUT http://localhost:8080/api/categories/135
Content-Type: application/json

{
   "productName": "New super product",
   "categoryId": 1,
   "quantityPerUnit": "5lb per pkg",
   "unitPrice": 28.98,
   "unitsInStock": 18,
   "unitsOnOrder": 20,
   "reorderLevel": 15
}

### GET invalid resource
GET http://localhost:8080/actors